-- V7: Add customer VIP discount and order discount columns (NCL-15-CN-003)
ALTER TABLE customers
    ADD COLUMN IF NOT EXISTS discount_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS discount_type VARCHAR(20) NOT NULL DEFAULT 'PERCENTAGE',
    ADD COLUMN IF NOT EXISTS total_spent DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS is_vip BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS customer_discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS promotion_discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00;
