import { ORDER_PAYMENT_METHOD, ORDER_STATUS } from "@/constants/order";
import type { IOrderResponse } from "@/modules/order/types/IOrder";

export const MOCK_ORDERS: IOrderResponse[] = [
  {
    id: "ord1",
    orderNumber: "DH-0001",
    householdId: "h1",
    shiftId: "s1",
    createdByUserId: "u1",
    createdByUsername: "nhanvien_viet",
    customerId: null,
    customerName: null,
    totalAmount: 120000,
    discountAmount: 10000,
    finalAmount: 110000,
    paymentMethod: ORDER_PAYMENT_METHOD.CASH,
    paymentStatus: "PAID",
    status: ORDER_STATUS.COMPLETED,
    syncStatus: "SYNCED",
    isOffline: false,
    syncedAt: "2026-07-15 09:15:00",
    createdAt: "2026-07-15 09:15:00",
    updatedAt: "2026-07-15 09:15:00",
    items: [
      {
        id: "item-1a",
        productId: "p1",
        productName: "Nước ngọt Coca-Cola lon 320ml",
        quantity: 10,
        unitPrice: 10000,
        discountAmount: 0,
        taxRatePercentage: 0,
        taxAmount: 0,
        subtotal: 100000,
      },
      {
        id: "item-1b",
        productId: "p2",
        productName: "Mì ăn liền Hảo Hảo Tôm Chua Cay",
        quantity: 4,
        unitPrice: 5000,
        discountAmount: 0,
        taxRatePercentage: 0,
        taxAmount: 0,
        subtotal: 20000,
      },
    ],
    warningMessages: [],
    qrCodeUrl: null,
    changeAmount: 0,
  },
  {
    id: "ord2",
    orderNumber: "DH-0002",
    householdId: "h1",
    shiftId: "s1",
    createdByUserId: "u1",
    createdByUsername: "nhanvien_viet",
    customerId: "c1",
    customerName: "Nguyễn Văn A",
    totalAmount: 250000,
    discountAmount: 20000,
    finalAmount: 230000,
    paymentMethod: ORDER_PAYMENT_METHOD.BANK_TRANSFER,
    paymentStatus: "PAID",
    status: ORDER_STATUS.COMPLETED,
    syncStatus: "SYNCED",
    isOffline: false,
    syncedAt: "2026-07-15 09:40:00",
    createdAt: "2026-07-15 09:40:00",
    updatedAt: "2026-07-15 09:40:00",
    items: [
      {
        id: "item-2a",
        productId: "p3",
        productName: "Sữa tắm Johnson's Baby 500ml",
        quantity: 2,
        unitPrice: 125000,
        discountAmount: 0,
        taxRatePercentage: 0,
        taxAmount: 0,
        subtotal: 250000,
      },
    ],
    warningMessages: [],
    qrCodeUrl: null,
    changeAmount: 0,
  },
];
